/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'primary': '#4a6549',
        'on-primary': '#ffffff',
        'primary-container': '#8ba888',
        'on-primary-container': '#243d24',
        'primary-fixed': '#ccebc7',
        'primary-fixed-dim': '#b0cfad',
        'on-primary-fixed': '#07200b',
        'on-primary-fixed-variant': '#334d33',

        'secondary': '#3e6378',
        'on-secondary': '#ffffff',
        'secondary-container': '#bfe5fe',
        'on-secondary-container': '#43677c',
        'secondary-fixed': '#c4e7ff',
        'secondary-fixed-dim': '#a6cce4',
        'on-secondary-fixed': '#001e2c',
        'on-secondary-fixed-variant': '#254b5f',

        'tertiary': '#6a5d45',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#af9e83',
        'on-tertiary-container': '#413520',
        'tertiary-fixed': '#f3e0c2',
        'tertiary-fixed-dim': '#d6c4a7',
        'on-tertiary-fixed': '#241a07',
        'on-tertiary-fixed-variant': '#51452f',

        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',

        'surface': '#fbf8fc',
        'on-surface': '#1b1b1e',
        'surface-variant': '#e3e2e6',
        'on-surface-variant': '#434841',
        'surface-container': '#efedf1',
        'surface-container-high': '#e9e7eb',
        'surface-container-highest': '#e3e2e6',
        'surface-container-low': '#f5f3f7',
        'surface-container-lowest': '#ffffff',
        'surface-bright': '#fbf8fc',
        'surface-dim': '#dbd9dd',
        'inverse-surface': '#303033',
        'inverse-on-surface': '#f2f0f4',

        'outline': '#737970',
        'outline-variant': '#c3c8bf',
        'background': '#fbf8fc',
        'on-background': '#1b1b1e',

        'inverse-primary': '#b0cfad',
        'surface-tint': '#4a6549',
      },
      spacing: {
        'xs': '4px',
        'sm': '12px',
        'base': '8px',
        'md': '24px',
        'lg': '48px',
        'xl': '80px',
        'gutter': '24px',
        'margin-mobile': '20px',
        'margin-desktop': '120px',
        'tc-sm': '0.5rem',
        'tc-safe': 'env(safe-area-inset-bottom)',
        'tc-margin-mobile': '1rem',
        'tc-margin-desktop': '2rem',
      },
      fontFamily: {
        'headline-lg': ['Quicksand', 'sans-serif'],
        'headline-md': ['Quicksand', 'sans-serif'],
        'headline-lg-mobile': ['Quicksand', 'sans-serif'],
        'body-lg': ['Lexend', 'sans-serif'],
        'body-md': ['Lexend', 'sans-serif'],
        'label-lg': ['Quicksand', 'sans-serif'],
        'label-md': ['Quicksand', 'sans-serif'],
        'tc-headline': ['Literata', 'serif'],
        'tc-display': ['Literata', 'serif'],
        'tc-body': ['Nunito Sans', 'sans-serif'],
        'tc-label': ['Nunito Sans', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-md': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'headline-lg-mobile': ['32px', { lineHeight: '38px', fontWeight: '800' }],
        'body-lg': ['20px', { lineHeight: '32px', fontWeight: '500' }],
        'body-md': ['18px', { lineHeight: '28px', fontWeight: '500' }],
        'label-lg': ['18px', { lineHeight: '24px', letterSpacing: '0.05em', fontWeight: '700' }],
        'label-md': ['16px', { lineHeight: '20px', fontWeight: '700' }],
        'tc-display-lg': ['4rem', { lineHeight: '4.5rem', letterSpacing: '-0.02em', fontWeight: '800' }],
        'tc-display-md': ['3rem', { lineHeight: '3.5rem', letterSpacing: '-0.01em', fontWeight: '800' }],
        'tc-headline-lg': ['2rem', { lineHeight: '2.5rem', fontWeight: '700' }],
        'tc-headline-lg-mobile': ['1.5rem', { lineHeight: '2rem', fontWeight: '700' }],
        'tc-label-lg': ['1rem', { lineHeight: '1.5rem', fontWeight: '700' }],
      },
      boxShadow: {
        'tc-soft': '0 4px 20px rgba(46, 50, 48, 0.06)',
        'tc-bouncy': '0 8px 0 rgba(42, 96, 56, 1)',
        'tc-bouncy-active': '0 0px 0 rgba(42, 96, 56, 1)',
      },
    },
  },
  plugins: [],
}
